### ISSUE TITLE
Needs birds

### ISSUE THREAD

**Issue by allthedoll** [Birds-Awesome-Org/Demo#5]
Put a birb on it

![birb](https://i.kym-cdn.com/entries/icons/original/000/019/189/birb.jpg)

**Comment by StephenCBird** [comment]
***Birb** huh?*
![bird's the word](https://i.imgflip.com/1aomq9.jpg)
Just closing out some issues and cleaning up the repo 😃 
Going to try and keep working on this in my free time.
Thanks for the issue. I'll be sure to add plenty of birbs in the future. 

🐦
